---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: install pexpect using pip
      shell: /bin/bash -c "pip install pexpect"
