- name: Install and configure AD authentication
  hosts: linux
  remote_user: root
  
  tasks:
    - name: Create directory to mount temporary shares to
        shell: /bin/bash -c "mkdir /mnt/tmp"   
