---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: install pexpect using pip
      shell: /bin/bash -c "mkdir /mnt/tmp"
      
    - name: disable firewalld service 
      shell: /bin/bash -c "service firwalld stop"
      
    - name: and stop it from starting at boot 
      shell: /bin/bash -c "chkconfig firewalld off"
      
