---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: install pexpect using pip
      shell: /bin/bash -c "mkdir /mnt/tmp"
      ignore_errors: yes

    - name: mount groups share
      shell: /bin/bash -c "mount -t cifs //g-star.raw/data/install -o username=_svc_compadd,domain=G-STAR.RAW,password=R@wadd00 /mnt/tmp"
     
    - name:  copy VMWARE Tools Installation
      shell: /bin/bash -c "cd /mnt/tmp/Server/Linux"
      
    - name: copy VMWare Tools Installation
      shell: /bin/bash -c "mkdir /tmp"
      ignore_errors: yes
      
    - name: copy VMWare Tools Installation
      shell: /bin/bash -c "cp VMwareTools-9.0.15-2323214.tar.gz /tmp"
      ignore_errors: yes
      
    - name: untar and run
      shell: /bin/bash -c "cd /tmp"
      
    - name: untar and run
      shell: /bin/bash -c "tar -zxvf VMwareTools-9.0.15-2323214.tar.gz"
      ignore_errors: yes
      
    - name: untar and run
      shell: /bin/bash -c "cd vmware-tools-distrib"
      
    - name: untar and run
      shell: /bin/bash -c "yum -y -q install perl gcc make kernel-headers kernel-devel -y"
      
    - name: untar and run
      shell: /bin/bash -c "yum -y -q install 'kernel-devel-uname-r == $(uname -r)'"
      
    - name: untar and run
      shell: /bin/bash -c "./vmware-install.pl -d default"
      
    - name: Install packages needed to join domain
      shell: /bin/bash -c "yum -y -q install realmd sssd oddjob oddjob-mkhomedir adcli samba-common"
      
    - name: Join system to Domain
      expect:
        command: /bin/bash -c "/usr/sbin/realm join G-STAR.RAW --use=_svc_compadd"
        responses: 
          Password For Administrator: "R@wadd00"
