---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: install pexpect using pip
      shell: /bin/bash -c "mkdir /mnt/tmp"

    - name: disable firewalld service and stop it from starting at boot
      shell: /bin/bash -c "service firwalld stop"
	  shell: /bin/bash -c "chkconfig firewalld off"

    - name: mount groups share
      shell: /bin/bash -c "mount -t cifs //g-star.raw/data/install -o username=_svc_compadd,domain=G-STAR.RAW,password=R@wadd00 /mnt/tmp"
