---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: install pexpect using pip
      shell: /bin/bash -c "mkdir /mnt/tmp"

    - name: mount groups share
     shell: /bin/bash -c "mount -t cifs //g-star.raw/data/install -o username=_svc_compadd,domain=G-STAR.RAW,password=R@wadd00 /mnt/tmp"
     
    - name:  copy VMWARE Tools Installation
     shell: /bin/bash -c "cd /mnt/tmp/Server/Linux"
     
