---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: install pexpect using pip
      shell: /bin/bash -c "mkdir /mnt/tmp"
      ignore_errors: yes

    - name: mount groups share
      shell: /bin/bash -c "mount -t cifs //g-star.raw/data/install -o username=_svc_compadd,domain=G-STAR.RAW,password=R@wadd00 /mnt/tmp"
     
    - name:  copy VMWARE Tools Installation
      shell: /bin/bash -c "cd /mnt/tmp/Server/Linux"
      
    - name: copy VMWare Tools Installation
      shell: /bin/bash -c "mkdir /tmp"
      
    - name: copy VMWare Tools Installation
      shell: /bin/bash -c "cp VMwareTools-9.0.15-2323214.tar.gz /tmp"
      
    - name: untar and run
      shell: /bin/bash -c "cd /tmp"
      
    - name: untar and run
      shell: /bin/bash -c "tar -zxvf VMwareTools-9.0.15-2323214.tar.gz"
      
    - name: 
