---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: change FQDN requirement logins
      lineinfile:
        destfile: /etc/sssd/sssd.conf
        regexp: '^use_fully_qualified_names = True'
        line: 'use_fully_qualified_names = False'
      
    - name: restart sssd to process changes
      service:
        name: sssd
        state: restarted
      
